name: Deploy to GitHub Pages

# Gatilhos: Quando o robo deve trabalhar
on:
  push:
    branches: ["main", "master"]
  workflow_dispatch:


# Permissões: o 'crachá" de acesso do robô
permissions:
  contents: read
  pages: write
  id-token: write

# Concorrência: Organiza a fila de deploys
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # O servidor (Runner): Onde a magica acontece
    runs-on: ubuntu-latest

    steps:
    #Passo 1: Baixa o seu código para o servidor
    - name: Checkout
      uses: actions/checkout@v4

    - name: Verificar pasta src
      run: |
        if [ -d "src" ]; then
          echo "Pasta src encontrada!"
        else
          echo "Pasta src NÃO encontrada!"
          exit 1
        fi

    - name: Verificar arquivo CSS
      run: |
        if [ -f "src/css/style.css" ]; then
          echo "Arquivo src/css/style.css encontrado!"
        else
          echo "Arquivo src/css/style.css NÃO encontrado!"
          exit 1
        fi

    #Passo 2: Explora o servidor (opcional)
    - name: Explorando o Runner
      run: |
        lsb_release -a
        free -h

    #Passo 3: Configura o ambiente para o GitHub Pages
    - name: Setup Pages
      uses: actions/configure-pages@v4

    #Passo 4: Empacota o site (HTML/CSS) paa o servidor teste teste
    - name: Deploy to gitHub Pages
      uses: actions/upload-pages-artifact@v4
      with:
        path: '.'

    #Passo5: Publica o site oficialmente
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
    
    - name: Validar sintaxe do HTML
      run: |
        npm install -g htmlhint
        htmlhint index.html

    # - name: Validar sintaxe do HTML
    #   uses: htmlhint/htmlhint-action@v2
    #   with:
    #     target_pattern: 'index.html'

    - name: Checar arquivos estáticos
      run: |
        ls -R
        echo "Todos os arquivos foram carregados no Runner!"s